using System;

namespace Shared.resources
{
    [Flags]
    public enum ConditionEffectIndex : byte
    {
        Nothing = 0,
        Dead = 1,
        Quiet = 2,
        Weak = 3,
        Slowed = 4,
        Sick = 5,
        Dazed = 6,
        Stunned = 7,
        Blind = 8,
        Hallucinating = 9,
        Drunk = 10,
        Confused = 11,
        StunImmune = 12,
        Invisible = 13,
        Paralyzed = 14,
        Speedy = 15,
        Bleeding = 16,
        ArmorBrokenImmune = 17,
        Healing = 18,
        Damaging = 19,
        Berserk = 20,
        Paused = 21,
        Stasis = 22,
        StasisImmune = 23,
        Invincible = 24,
        Invulnerable = 25,
        Armored = 26,
        ArmorBroken = 27,
        Hexed = 28,
        NinjaSpeedy = 29,
        Unstable = 30,
        Darkness = 31,
        SlowedImmune = 32,
        DazedImmune = 33,
        ParalyzedImmune = 34,
        Petrify = 35,
        PetrifiedImmune = 36,
        PetEffectIcon = 37,
        Curse = 38,
        CurseImmune = 39,
        HpBoost = 40,
        MpBoost = 41,
        AttBoost = 42,
        DefBoost = 43,
        SpdBoost = 44,
        VitBoost = 45,
        WisBoost = 46,
        DexBoost = 47,
        Silenced = 48,
        Exposed = 49,
        Energized = 50,
        HpDebuff = 51,
        MpDebuff = 52,
        AttDebuff = 53,
        DefDebuff = 54,
        SpdDebuff = 55,
        VitDebuff = 56,
        WisDebuff = 57,
        DexDebuff = 58,
        Inspired = 59,
        ManaDeplete = 60,
        ConditionCount
    }
}
